name: "Shortify Git Revision"
description: "Github Action to shortify a git revision"
author: "Romain Lespinasse"
inputs:
  name:
    description: "Environment variable that will hold the value and serve as prefix to shortify value"
    required: true
  revision:
    description: "Revision to short"
    required: false
  continue-on-error:
    description: "Don't fail the action if the git revision isn't valid"
    default: "false"
    required: false
  prefix:
    description: "Value to prepend to each generated variable"
    default: ""
    required: false
  length:
    description: "Value to configure the length of the shorted sha"
    default: ""
    required: false
branding:
  icon: "crop"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/shortify.sh
      shell: bash
      env:
        INPUT_NAME: ${{ inputs.name }}
        INPUT_REVISION: ${{ inputs.revision }}
        INPUT_CONTINUE_ON_ERROR: ${{ inputs.continue-on-error }}
        INPUT_PREFIX: ${{ inputs.prefix }}
        INPUT_LENGTH: ${{ inputs.length }}
