name: Shortify git revision testing
on: [push]
jobs:
  shortify-git-revision-on-os:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: shortify-git-revision-on-os-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Test 1
      - name: Shortify an existing git revision
        uses: ./
        with:
          name: ROOT_COMMIT
          revision: 88428f56bd9d2751c47106bedfd148162dfa50b8
      - name: Validate // Shortify an existing git revision
        run: |
          [[ "${{ env.ROOT_COMMIT }}" == "88428f56bd9d2751c47106bedfd148162dfa50b8" ]]
          [[ "${{ env.ROOT_COMMIT_SHORT }}" == "88428f5" ]]
        shell: bash

      # Test 2
      - name: Shortify an existing git revision from an env variable
        uses: ./
        with:
          name: ENV_VAR_COMMIT
        env:
          ENV_VAR_COMMIT: 88428f56bd9d2751c47106bedfd148162dfa50b8
      - name: Validate // Shortify an existing git revision from an env variable
        run: |
          [[ "${{ env.ENV_VAR_COMMIT }}" == "88428f56bd9d2751c47106bedfd148162dfa50b8" ]]
          [[ "${{ env.ENV_VAR_COMMIT_SHORT }}" == "88428f5" ]]
        shell: bash

      # Test 3
      - name: Shortify a missing git revision
        uses: ./
        with:
          name: MISSING_REVISION
          revision: ""
      - name: Validate // Shortify a missing git revision
        run: |
          [[ -z "${{ env.MISSING_REVISION }}" ]]
          [[ -z "${{ env.MISSING_REVISION_SHORT }}" ]]
        shell: bash

      # Test 4
      - id: test-shortify-wrong-git-revision
        name: Shortify a wrong git revision
        uses: ./
        with:
          name: WRONG_REVISION
          revision: wrongwrongwrongwrongwrongwrongwrongwrong
        continue-on-error: true
      - name: Validate // Shortify a wrong git revision
        run: |
          [[ -z "${{ env.WRONG_REVISION }}" ]]
          [[ -z "${{ env.WRONG_REVISION_SHORT }}" ]]
          [[ "${{ steps.test-shortify-wrong-git-revision.outcome }}" == "failure" ]]
          [[ "${{ steps.test-shortify-wrong-git-revision.conclusion }}" == "success" ]]
        shell: bash

      # Test 5
      - name: Shortify a wrong git revision without failing
        uses: ./
        with:
          name: WRONG_AND_MISSING_REVISION
          revision: wrongwrongwrongwrongwrongwrongwrongwrong
          continue-on-error: true
      - name: Validate // Shortify a wrong git revision without failing
        run: |
          [[ -z "${{ env.WRONG_AND_MISSING_REVISION }}" ]]
          [[ -z "${{ env.WRONG_AND_MISSING_REVISION_SHORT }}" ]]
        shell: bash

  shortify-git-revision-release:
    runs-on: ubuntu-latest
    concurrency:
      group: shortify-git-revision-release-${{ github.ref }}
    needs: shortify-git-revision-on-os
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Release
      - name: Release this GitHub Action
        uses: rlespinasse/release-that@v1.x
